add solution for 01-basics 01-CounterButton
js-tasks-ru/vue-20201022_veryaskinadi pull request #2
Opened 2020-10-27 12:31 UTC by veryaskinadi

2020-10-27 13:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-27 13:46 UTC, ShGKme requested changes
Задача CounterButton принята.
Требуется решить все добавленные задачи, чтобы PR был принят...

2020-10-27 13:46 UTC, ShGKme commented on 01-basics/01-CounterButton/index.html
> +  <button v-on:click = "count" >{{num}}</button>
Лучше всегда использовать короткую запись `@click`. А внутри {{}} добавлять отступ пробелом: `{{ num }}`.

2020-10-27 13:46 UTC, ShGKme commented on 01-basics/01-CounterButton/script.js
> +    },
Описание data объектом удалено из Vue 3, работает только функция, возвращающая объект

2020-10-28 12:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-28 18:15 UTC, ShGKme approved these changes
Принято, но есть комментарии.

2020-10-28 18:15 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +      meetup: {}
На вебинаре мы начальным значением массива устанавливали пустой массив. Это корректно, пустой массив митапов - это частный случай массива митапов. Но пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в {} избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

2020-10-28 18:15 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +        agendaItem.icon = 'icon' + '-' + agendaItemIcons[agendaItem.type] + '.' + 'svg'
Лучше использовать шаблонные строки: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings

2020-10-28 18:15 UTC, merged